import mongoose, { Schema } from "mongoose";
import bcrypt from "bcrypt"; // the package we use to hash things, can be used to hash passwords and any other fields
import jwt from "jsonwebtoken"; // need to install it from npm
import crypto from "node:crypto"; // can either say "crypto" or "node:crypto"

// for the Schema class you are also use it like mongoose.Schema OR import it directly here as shown

const userSchema = new Schema(
  {
    avatar: {
      // each of the field, in this case avatar requires a 'type' to be given
      type: {
        url: String,
        localPath: String, // keeping this image file in local storage
      },
      default: {
        url: `https://placehold.co/200x200`,
        localPath: "",
      },
    },

    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true, // all names are in lower names
      trim: true, // trims the trailing spaces
      index: true, // optimise for searching??
    },

    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },

    fullName: {
      type: String,
      trim: true,
    },

    password: {
      type: String,
      required: [true, "Password is required"], // you can set a custom error if person does NOT provide it
    },

    isEmailVerified: {
      type: Boolean,
      default: false, // no one is verified by default
    },

    // use JWT tokens?
    refreshToken: {
      type: String,
    },

    forgotPasswordToken: {
      type: String,
    },

    forgotPasswordExpiry: {
      type: Date,
    },

    emailVerificationToken: {
      type: String,
    },

    emailVerificationExpiry: {
      type: Date,
    },
  },
  {
    timestamps: true, // this will make the fields CreatedAt and UpdatedAt available.
  },
);

// Schema is a class that takes an object, the object is to contain all of the fields and validation? of the schema.
/* 
1. the first object in that schema object contains all the fields
2. second object contains the timestamps field
you can also attach 'write methods' & 'hooks' to your schema
*/

userSchema.pre("save", async function (next) {
  // next keyword here is saying im done with this step move on to the next hook or whatever step downstream like controllers or smth / request etc..?

  if (!this.isModified("password")) {
    return next(); // don't proceed to the below steps if it is not the password field being modified
  }

  this.password = await bcrypt.hash(this.password, 10); // 10 means how many rounds of hashing you want to do, and then we overwrite the password. IMPORTANT: RIGHT NOW EVERY TIME WE SAVE OR UPDATE DATA LIKE EMAIL OR WHATEVER THE PRE-HOOK WILL RUN, AND THAT MEANS OUR PASSWORD IS ENCRYPTED / HASHED EACH TIME. we need a check to ensure password is hashed ONLY when pw is changed / first time user entering the password.
  next();
});

// ^ attach the pre-hook to the SAVE operation, and use a function NOT an arrow function as we need the context of it

// attach METHODS to the schema, 'isPasswordCorrect' is the name for this method, can be anything.
userSchema.methods.isPasswordCorrect = async function (password) {
  // password is the one that the user entered when they login or smth
  return await bcrypt.compare(password, this.password); // a true or false value is returned depending on whether the password is matched.
};

// note it is 'methods' NOT 'method'!
userSchema.methods.generateAccessToken = function () {
  // we use 'return' so whoever uses this method receives back a token
  return jwt.sign(
    // this is the payload, aka the info we are storing, usually _id is sufficient
    {
      _id: this._id, // _id is auto generated by mongoDB
      email: this.email,
      username: this.username,
    },
    // second part is the secret
    process.env.ACCESS_TOKEN_SECRET,
    // add the expiry
    { expiresIn: process.env.ACCESS_TOKEN_EXPIRY },
  );
};

// the way to generate a refresh token is the same as access token
userSchema.methods.generateRefreshToken = function () {
  return jwt.sign(
    // payload for refresh token is very short, so usually _id is sufficient
    {
      _id: this._id,
    },
    process.env.REFRESH_TOKEN_SECRET,
    { expiresIn: process.env.REFRESH_TOKEN_EXPIRY },
  );
};

// generate 'without data tokens' aka just a random string
userSchema.methods.generateTemporaryToken = function () {
  const unHashedToken = crypto.randomBytes(20).toString("hex"); // this means im converting the hexa decimal numbers from the crypto.randomBytes to a string??

  const hashedToken = crypto
    .createHash("sha256")
    .update(unHashedToken)
    .digest("hex"); // what's a digest??

  const tokenExpiry = Date.now() + 20 * 60 * 1000; // add 20 mins

  // when we use this method in the controller it will return us the expiry time field and other info and we will store this info in that controller script
  return { unHashedToken, hashedToken, tokenExpiry };
};

export const User = mongoose.model("User", userSchema); // but mongoose will auto-convert the name from "User" to users, and also you need to specify to use WHICH schema to create the schema, and in this case it is 'userSchema'
